name: Build and Release
on: push

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-build -o build
      
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: build
          if-no-files-found: error
  
  build-windows:
    name: Build Windows
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"
      
      - name: Restore
        run: dotnet restore -r win-x64

      - name: Build
        run: dotnet build -r win-x64 -c Release --no-restore

      - name: Publish
        run: dotnet publish -r win-x64 -c Release --no-build -o build
      
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: build
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    if: startsWith(github.ref, 'refs/tags/')
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: build-linux
    
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: build-windows
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with: 
          files: |
            build-linux/EXDTooler
            build-linux/EXDTooler.pdb
            build-windows/EXDTooler.exe
