name: Release Tools
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Define version
        id: define-version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x.x'
      - name: Build
        run: dotnet build -c Release
      - name: Create Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          mkdir release-out
          Compress-Archive -Path .\BasicSchemaGenerator\bin\Release\net7.0-windows\* -DestinationPath .\release-out\BasicSchemaGenerator.zip -Force
          Compress-Archive -Path .\DirectoryManager\bin\Release\net7.0-windows\* -DestinationPath .\release-out\DirectoryManager.zip -Force
          Compress-Archive -Path .\SchemaConverter\bin\Release\net7.0-windows\* -DestinationPath .\release-out\SchemaConverter.zip -Force
          Compress-Archive -Path .\SchemaValidator\bin\Release\net7.0-windows\* -DestinationPath .\release-out\SchemaValidator.zip -Force
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release-out/**
          name: Release for ${{ steps.define-version.outputs.commit }}
          tag_name:  ${{ steps.define-version.outputs.version }}