name: Release Tools
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Define version
        id: define-version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Build
        run: dotnet build -c Release
      - name: Create Release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          mkdir release-out
          zip -r release-out/BasicSchemaGenerator.zip BasicSchemaGenerator/bin/Release/net7.0/
          zip -r release-out/DirectoryManager.zip DirectoryManager/bin/Release/net7.0/
          zip -r release-out/SchemaConverter.zip SchemaConverter/bin/Release/net7.0/
          zip -r release-out/SchemaValidator.zip SchemaValidator/bin/Release/net7.0/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release-out/**
          name: Release for ${{ steps.define-version.outputs.commit }}
          tag_name:  ${{ steps.define-version.outputs.version }}